### Stage 2 scoring components
[[component]]
[component.ChemPropFORMED]

[[component.ChemPropFORMED.endpoint]]
name = "energy_score"
weight = 1.3

params.checkpoint_dir = "../chemprop_model/formed_chemprop/fold_0/model_0/"
params.rdkit_2d_normalized = false

transform.type = "sigmoid"
transform.high = 5
transform.low = -10
transform.k = 0.4


[[component]]
[component.ChemProp]

[[component.ChemProp.endpoint]]
name = "exciton_size"
weight = 0.5

params.checkpoint_dir = "../chemprop_model/formed_shdist/fold_0/model_0/"
params.rdkit_2d_normalized = false

transform.type = "sigmoid"
transform.high = 10
transform.low = 0
transform.k = 0.4


[[component]]
[component.ChemPropFORMEDT1T2]

[[component.ChemPropFORMEDT1T2.endpoint]]
name = "T2-T1"
weight = 0.4

params.checkpoint_dir = "../chemprop_model/formed_t1t2/fold_0/model_0/"
params.rdkit_2d_normalized = false

transform.type = "sigmoid"
transform.high = 10
transform.low = 0
transform.k = 0.4




[[component]]
# Custom alerts if used in a custom_product filter out unwanted groups
[component.custom_alerts]

[[component.custom_alerts.endpoint]]
name = "Unwanted SMARTS"  # user chosen name for output
weight = 2 # weight to fine-tune the relevance of this component

# parameters for the component:
# a list of unwanted SMARTS(!) to be scored as zero
params.smarts = [
    "[*;r8]",
    "[*;r9]",
    "[*;r10]",
    "[*;r11]",
    "[*;r12]",
    "[*;r13]",
    "[*;r14]",
    "[*;r15]",
    "[*;r16]",
    "[*;r17]",
    "[C;!R]=[C;!R]~[C;!R]=[C;!R]~[C;!R]=[C;!R]", #!! ( ๑‾̀◡‾́)σ"
    "[C;!R]=[C;!R]~[C;!R]=[C;!R]~[C;!R]", #!! ( ๑‾̀◡‾́)σ"
    "[*;r]-[C;!R]=[C;!R][*;r]",
    "[*;r]-[C;!R]=[C;!R]~[C;!R]=[C;!R][*;r]",
    "[7][5](F)(F)[7]",
    "[7][7]",
    
]


[[component]]
[component.ForceNeutral]
[[component.ForceNeutral.endpoint]]
name = "neutral_mol"
weight = 0.4



